# Site settings
title: Tarek Swaidane blog
email: 
description: "Computer Scientist."
baseurl: ""
url: "http://tareksw.github.io"
twitter_username: TarekSwaidane
github_username:  TarekSw

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
