# Site settings
title: Tarek Sw blog
email: 
description: "Computer Scientist."
baseurl: ""
url: "https://tareksw.github.io/"
twitter_username: tarek_swaidane
github_username:  TarekSw
linkedin_username:  tarek-swaidane

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
